### ISSUE TITLE
Disenchant Distribution including Nexus Crystals...

### ISSUE THREAD

**Issue by kakkakk** [shirsig/aux-addon#269]
... which of course are not in the game yet, and is making disenchant values useless for higher level items. Is this easily fixable by editing a lua file on my end? Thanks!

**Comment by shirsig** [comment]
It should already have been fixed recently, at least for items where the chance for a nexus crystal is small, because i changed the unavailable prices from disabling the value to counting as 0.

**Comment by kakkakk** [comment]
Hi Thanks for the quick reply! I'm using the most recent download, and Nexus Crystals were still showing in the tooltip. I actually managed to find the values in the disenchant.lua file and manually change them, and being the novice to this sort of thing that I am, I'm quite proud of myself for managing this lol

**Comment by shirsig** [comment]
Oh yeah i was only talking about the value not the distribution, sorry. I guess the best generic solution will be to make the nexus crystal a shard as long as there is no value for the nexus crystal.

**Comment by kakkakk** [comment]
Yeah I believe all 55+ level blues are 100% to turn into a Large Brilliant shard. I'm not sure about 60 epics, if they turn into 1 or 2 or 3, etc.

**Comment by kakkakk** [comment]
Trying to figure out how to build filters for searching for AH items that are worth disenchanting and this was bugging me, is all.

**Comment by shirsig** [comment]
obsolete now.
